baseURL = "https://hookszhang.space/"
languageCode = "zh-CN"
title = "Hooks Zhang's Blog"
theme = "minimal"
disqusShortname = "hookszhang-space" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Hooks Zhang"
    description = "技术狂热分子"
    githubUsername = "hookszhang"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "github"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    baiduAnalytics = "934435e81e770336b65f19074823a8ae"

[[menu.main]]
    url = "/"
    name = "首页"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "文章"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:hookszhang@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/hookszhang/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://stackoverflow.com/users/4715098/hooks-zhang"
    name = "stack-overflow"
    weight = 5
